before_install:
- git submodule update --init --recursive
- git clone https://github.com/smcgregor/privly-web.git # clone the webserver
language: ruby
rvm:
- 1.9.3
env:
  global:
  - DB=mysql
  - TRAVIS_LAUNCHES_SAUCE_CONNECT=true # Tell the karma file that it does not need to launch Sauce connect
  - secure: "mVySvTZJu/TnfYQvn2YVRfLByBlVtw0hu5OIyDd6qnHBS+MYehEgq6Q2xP61eG97xuou9LKTLnCG7aYHPKU91g3kVC1//WxCjRu4mjkZC8lqq5d3FQNKHIWXvvov6ReP+RHUpq4hoGhwm3jWAregIsEGhUapEyfqzhsI+8uVrwA=" # SAUCE_URL=
  - RAILS_ENV=development
script:
- ruby test/selenium/run_all.rb -p sauce_firefox_extension -c http://localhost:3000
before_script:
- cd privly-web
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database privly_test'
- bundle install #Installs the required gems
- rake db:create #Creates the Database
- rake db:schema:load #Loads the Scheme
- rake db:seed #Seeds the DB
- "bundle exec rails server -p 3000 &"
- cd ../chrome/content/privly-applications
addons:
  sauce_connect:
    username: privly
    access_key:
      secure: "Q/QojWavKrUVKy/Hy7oj0TwA91+h4j/oytswut5qr9+WJ+uyMCScVjY+ri8xaukbzTOj6UhQxFu61bDSJWgq2LFYHf/gtEEYdfn9Hv4h9mU27XAbS91YuqOdCRsyB7E6iUqoCXq+kUa8rpeRD8GiENSTXdpYbOogxIMtQrF6geE="
